//CAROLINA ETCHART - 278963
//MARIA EUGENIA MATTO - 227056
package interfaz;

import dominio.*;
import javax.swing.*;

public class VentanaPedidos extends javax.swing.JFrame {

    private Rotiseria rot;
    private DefaultListModel pedidos; //lista pedidos
    private DefaultListModel productos;//lista productos

    /**
     * Creates new form VentanaPedidos
     */
    public VentanaPedidos() {
        initComponents();
    }

    public VentanaPedidos(Rotiseria unaRotiseria) {
        rot = unaRotiseria;
        pedidos = new DefaultListModel();
        productos =  new DefaultListModel();
        initComponents();
        pedidos.clear();
        productos.clear();
        for(Pedido p: rot.getListaPedidos()){
            
            pedidos.addElement(p.toString());
        }
        listaPedidos.setModel(pedidos);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneListaPedidos = new javax.swing.JScrollPane();
        listaPedidos = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        labelTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelObservaciones = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblObservaciones = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();

        jLabel1.setText("Total: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PEDIDOS");
        getContentPane().setLayout(new java.awt.CardLayout(20, 20));

        pnlPanel.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.CardLayout(30, 0));

        listaPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPedidosValueChanged(evt);
            }
        });
        jScrollPaneListaPedidos.setViewportView(listaPedidos);

        jPanel1.add(jScrollPaneListaPedidos, "card2");

        pnlPanel.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("Total:  $");
        jPanel6.add(labelTotal);

        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.add(lblTotal);

        jPanel3.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(1, 1));

        labelObservaciones.setText("Observaciones: ");
        labelObservaciones.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel8.add(labelObservaciones);

        jPanel3.add(jPanel8);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        lblObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.add(lblObservaciones);

        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        lblProductos.setText("Productos:");
        jPanel9.add(lblProductos);

        jPanel4.add(jPanel9);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.CardLayout());

        jScrollPane1.setViewportView(listaProductos);

        jPanel5.add(jScrollPane1, "card2");

        jPanel2.add(jPanel5);

        pnlPanel.add(jPanel2);

        getContentPane().add(pnlPanel, "card2");

        setBounds(0, 0, 738, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void listaPedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPedidosValueChanged
        Pedido p = rot.buscarPedido(listaPedidos.getSelectedValue().toString());
        lblTotal.setText(p.getTotal()+"");
        lblObservaciones.setText(p.getObservaciones());
        productos.clear();
        for(int i=0; i<p.getListaProductos().size(); i++){
            productos.addElement(p.getListaProductos().get(i).toString());
        }   
        listaProductos.setModel(productos);
        
    }//GEN-LAST:event_listaPedidosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneListaPedidos;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList listaPedidos;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JPanel pnlPanel;
    // End of variables declaration//GEN-END:variables
}
