//CAROLINA ETCHART - 278963
//MARIA EUGENIA MATTO - 227056
package interfaz;

import dominio.*;
import javax.swing.*;

public class VentanaElegirCliente extends javax.swing.JFrame{

    private Rotiseria rot;

    /**
     * Creates new form VentanaElegirCliente
     */
    public VentanaElegirCliente() {
        initComponents();
    }
    
    public VentanaElegirCliente(Rotiseria unaRotiseria) {
        rot = unaRotiseria;
        initComponents();
        listaClientes.setListData(rot.getListaClientes().toArray());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        listClientes = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtClienteABuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnElegir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ELEGIR CLIENTE");
        getContentPane().setLayout(new java.awt.CardLayout(20, 20));

        pnlPanel.setLayout(new java.awt.GridLayout(3, 1));

        listClientes.setViewportView(listaClientes);

        pnlPanel.add(listClientes);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        txtClienteABuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtClienteABuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);

        jPanel2.add(jPanel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel11);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        jPanel5.add(btnReiniciar);

        jPanel2.add(jPanel5);

        pnlPanel.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jPanel6.setLayout(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8);
        jPanel8.setBounds(0, 0, 597, 36);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel12);

        btnElegir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        jPanel7.add(btnElegir);

        jPanel3.add(jPanel7);

        pnlPanel.add(jPanel3);

        getContentPane().add(pnlPanel, "card2");

        setBounds(0, 0, 653, 411);
    }// </editor-fold>//GEN-END:initComponents

    //BTN CONFIRMAR
    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        if(listaClientes.isSelectionEmpty()){
                JOptionPane.showMessageDialog(null,"Seleccione un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if(masDe1Seleccionado()){
                JOptionPane.showMessageDialog(null,"Más de un cliente seleccionado, seleccione solo uno.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                Cliente c = (Cliente) listaClientes.getSelectedValue();
                rot.setClienteActual(c);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Cliente seleccionado: "+c.getNombre(), "Atención", JOptionPane.INFORMATION_MESSAGE);
            }
    }
        
        
    }//GEN-LAST:event_btnElegirActionPerformed

    private boolean masDe1Seleccionado(){
        Object[] selecs = listaClientes.getSelectedValues();
        boolean si = false;
        if(selecs.length>1){
            si = true;
        }
        return si;
    }
    
    //BTN BUSCAR
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String cliente = txtClienteABuscar.getText();
       Cliente cc = null;
       for(int i = 0 ; i<rot.getListaClientes().size() ; i++){
           if(rot.getListaClientes().get(i).toString().toLowerCase().contains(cliente.toString().toLowerCase())){
               cc = rot.getListaClientes().get(i);
           }
       }
       listaClientes.setSelectedValue(cc, true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    //BTN REINICIAR
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        txtClienteABuscar.setText("");
        listaClientes.setSelectedValue(null, rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnReiniciarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane listClientes;
    private javax.swing.JList listaClientes;
    private javax.swing.JPanel pnlPanel;
    private javax.swing.JTextField txtClienteABuscar;
    // End of variables declaration//GEN-END:variables
}
